# Generated by Django 4.1.4 on 2022-12-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='names',
            new_name='Admins',
        ),
    ]
