# Generated by Django 4.1.4 on 2023-01-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_admins_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
