# Generated by Django 4.1.4 on 2023-01-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_admins_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDname', models.CharField(max_length=15)),
                ('PRDnumber', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
