# Generated by Django 4.1.4 on 2023-01-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_alter_admins_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDimage',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
