# Generated by Django 4.1.4 on 2023-01-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_prdimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Admins',
        ),
        migrations.RemoveField(
            model_name='product',
            name='PRDimage',
        ),
    ]
