# Generated by Django 4.1.4 on 2023-01-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_product_admins_remove_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
