# Generated by Django 4.1.4 on 2023-01-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_product_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Admins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.admins'),
            preserve_default=False,
        ),
    ]
