# Generated by Django 4.1.4 on 2023-01-02 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_product_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='username',
        ),
        migrations.AddField(
            model_name='admins',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
