# Generated by Django 4.1.4 on 2023-01-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_admins_password_remove_admins_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='user',
        ),
        migrations.AddField(
            model_name='admins',
            name='password',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admins',
            name='username',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
