# Generated by Django 4.1.4 on 2023-01-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_admins_user_admins_password_admins_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='category',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admins',
            name='storename',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
