# Generated by Django 4.1.4 on 2023-01-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_admins_category_admins_storename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='category',
        ),
    ]
