# Generated by Django 4.1.4 on 2023-01-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_admins_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='category',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
