# Generated by Django 4.1.4 on 2023-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_admins_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
