# Generated by Django 4.1.4 on 2023-01-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_admins_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='level',
            field=models.CharField(choices=[('JR', 'Junior'), ('ML', 'Middle'), ('SR', 'Senior')], default='JR', max_length=2),
        ),
    ]
