# Generated by Django 4.1.4 on 2023-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_admins_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='level',
        ),
        migrations.AlterField(
            model_name='admins',
            name='category',
            field=models.CharField(choices=[('fashion', 'fashion'), ('Cars', 'Cars'), ('fitness', 'fitness')], default='fashion', max_length=8),
        ),
    ]
