# Generated by Django 4.1.4 on 2023-01-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_admins_level_alter_admins_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='category111',
            field=models.CharField(choices=[('fashion', 'fashion'), ('Cars', 'Cars'), ('fitness', 'fitness')], default='fashion', max_length=8),
        ),
        migrations.AlterField(
            model_name='admins',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
