# Generated by Django 4.1.4 on 2023-01-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_admins_category111_alter_admins_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='category111',
        ),
    ]
