# Generated by Django 4.1.4 on 2023-01-06 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_admins_storecolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orNumber', models.CharField(max_length=15)),
                ('total', models.CharField(max_length=15)),
                ('Admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.admins')),
                ('products', models.ManyToManyField(to='base.product')),
            ],
        ),
    ]
