# Generated by Django 4.1.4 on 2023-01-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
