# Generated by Django 4.1.4 on 2023-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='totalprice',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
