# Generated by Django 4.1.4 on 2023-01-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_admins_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
