# Generated by Django 4.1.4 on 2023-01-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_product_prdimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDimage',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
