# Generated by Django 3.0.14 on 2023-01-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20230116_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
