# Generated by Django 3.0.14 on 2023-01-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_admins_storetextcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Admins')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.User')),
            ],
        ),
    ]
