# Generated by Django 4.1.4 on 2023-01-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_order_products_order_products'),
        ('base', '0047_auto_20230117_2221'),
    ]

    operations = [
    ]
