# Generated by Django 4.1.4 on 2023-01-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_remove_cart_admin_cart_admins_alter_admins_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='customer',
        ),
    ]
