# Generated by Django 4.1.4 on 2023-02-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_remove_customer_email_completedorder_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='Admins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.admins'),
            preserve_default=False,
        ),
    ]
