# Generated by Django 4.1.4 on 2023-02-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_alter_admins_id_alter_completedorder_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
