# Generated by Django 4.1.4 on 2023-02-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_admins_storephone_admins_storeemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='category',
        ),
    ]
