# Generated by Django 3.0.14 on 2023-02-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_remove_admins_storebackgroundcolor'),
        ('base', '0077_auto_20230211_1703'),
    ]

    operations = [
    ]
