# Generated by Django 4.1.4 on 2023-02-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_remove_admins_storebackgroundcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDnumber',
            field=models.IntegerField(unique=True),
        ),
    ]
