# Generated by Django 4.1.4 on 2023-02-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_alter_admins_email_alter_admins_username_and_more'),
        ('base', '0079_auto_20230212_1952'),
    ]

    operations = [
    ]
